Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "tomcat.example.com"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.puppet_install.puppet_version = :latest
  # r10k plugin to deploy puppet modules
  config.r10k.puppet_dir = "r10k"
  config.r10k.puppetfile_path = "r10k/Puppetfile"

  config.vm.synced_folder "modules/", "/opt/puppetlabs/puppet/modules"

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file = "tomcat.pp"
    puppet.module_path = "modules"
    # debug
    # puppet.options = "--verbose --debug"
  end

end
