mod 'stdlib',
  :git => 'https://github.com/puppetlabs/puppetlabs-stdlib'
mod 'concat',
  :git => 'https://github.com/puppetlabs/puppetlabs-concat'
mod 'archive',
  :git => 'https://github.com/voxpupuli/puppet-archive'
mod 'tomcat',
  :git => 'https://github.com/puppetlabs/puppetlabs-tomcat'
